### ISSUE TITLE
Availability outside Unity

### ISSUE THREAD

**Issue by gon** [Evryway/lir#2]
What would it take to make this algorithm available outside Unity? Ideally it would be a NuGet package one can add to their project.

Although I'm able to reference Unity as a NuGet package, Unity.Mathematics hasn't been packaged yet and can't be easily added.

Instead I tried to look for other packages which may provide alternative implementations of `int2` and `float2x2` struct types without much luck.

Thanks!

**Comment by andrewheumann** [comment]
I created a version of this package that runs on the open source Hypar.Elements library: https://github.com/hypar-io/LargestInteriorRectangle/

**Comment by gon** [comment]
Beautiful, thank you @andrewheumann.

**Comment by Evryway** [comment]
A replacement math implementation for the Unity built-in types would be required (as per @andrewheumann 's implementation above). Hopefully that fills your needs. If not, there are some other .NET math libraries that may work instead (potentially https://github.com/john-h-k/MathSharp or https://github.com/vimaec/Math3D) - you would need to try them out, you're free to fork and experiment.
