### ISSUE TITLE
Exception using the following points

### ISSUE THREAD

**Issue by Joe-houghton** [Evryway/lir#3]
Hi,

I am getting an System.IndexOutOfRangeException in LargestInteriorRectangle.cs using the following polygon:

496847.2188 | 181705.7188
496847.2188 | 181712.2656
496852.5938 | 181712.2813
496855.8438 | 181712.2813
496855.8438 | 181713.7813
496861.0313 | 181713.7969
496861.125 | 181702.0781
496861.125 | 181701.8281
496858.4688 | 181701.8125
496857.4063 | 181701.8125
496854.0313 | 181701.8125
496854 | 181705.7344
496852.6563 | 181705.7188
496852.7188 | 181701.2188
496849.1875 | 181701.2188
496847.1875 | 181701.2188
496847.1875 | 181704.25
496849.1875 | 181704.25
496849.1875 | 181705.7188
496847.2188 | 181705.7188

![image](https://user-images.githubusercontent.com/6493005/212959687-4c65861e-5161-4195-bd2f-683b5f8a3060.png)

Kind Regards

**Comment by Joe-houghton** [comment]
Ah, I have found that it works if I translate it to 0,0. Thanks.

**Comment by Evryway** [comment]
Thanks for raising this, @Joe-houghton . All my datasets were natually based around the origin, an ideal first step would be to centre around origin (as you have done) and then translate the resulting bound back to the original position. I'll look at implementing this in a future version.
