### ISSUE TITLE
Some cases throwing IndexOfOutRangeException

### ISSUE THREAD

**Issue by Joe-houghton** [Evryway/lir#4]
Hi again,

I think I have found an issue with the algorithm. I believe this is due to multiple vertices along the same line. i.e. the dark blue point on the middle right.

Here are the coordinates for the shape:

-6.012309074, -2.394122601
0.561122477, -2.394122601
0.56188339, -8.094342232
0.562643945, -13.79456139
-6.010787487, -13.79456139
-9.057126045, -13.79471302
-9.05653286, -9.563955307
-6.010194302, -9.563802719
-6.010483265, -8.186531067
-10.22067451, -8.238635063
-10.22199726, -2.395780802
-6.012309074, -2.394122601

![image](https://user-images.githubusercontent.com/6493005/214278287-05d7461c-d4d1-4df0-8749-6061ce67f5a6.png)

Currently I am just checking whether the index is within range and continuing on the loop.

Regards,

Joe

**Comment by Joe-houghton** [comment]
Here is another case

7.525075341, 18.03584103
8.873593212, 18.03584103
14.71882603, 18.04310901
20.09109498, 18.04807795
20.09109579, 11.30548939
20.08379922, 7.390946768
20.07960213, 4.904943037
14.8398342, 4.913811439
14.81097304, 4.913967396
14.81516979, 7.399971046
14.77711302, 11.31475831
8.897990992, 11.31980019
7.517957187, 11.32239571
7.517823608, 11.16280541
7.512232756, 6.440598359
2.821927548, 6.425158617
2.781571511, 9.5992437
2.761771935, 11.32380416
-2.768077453, 11.33181232
-2.756213328, 18.02582882
2.708230927, 18.03272605
2.707296381, 19.4777793
5.773485434, 19.47942581
5.774419978, 18.03437257
7.525075341, 18.03584103

![image](https://user-images.githubusercontent.com/6493005/214284844-928cf068-da5d-4e20-89e4-4203c3d3148e.png)

**Comment by Evryway** [comment]
Hi @Joe-houghton , I've added some tests and a general TestPolygon utility to help address this issue. There were two identified problems with the point sets you're using to describe your polygons - they have duplicate points (start and end point are duplicated) and the winding order is clockwise, where it should be counterclockwise.
If you look at the two test cases, you'll see that reversing the points and removing the duplicate will result in a valid output.

**Comment by Joe-houghton** [comment]
Thats great, Thanks @Evryway !
