### ISSUE TITLE
The Current Approach Is Not Robust Enough

### ISSUE THREAD

**Issue by ficapy** [Evryway/lir#6]
Thank you very much for your excellent blog and code, which have inspired me greatly. I have noticed a small issue:

1. The cell internal labeling process is not robust
    Labeling non-inner rectangles separately from the top, bottom, left, and right might yield incorrect results under special circumstances. For example:
    ```c#
   new Vector2(2,0),
   new Vector2(2, 9),
   new Vector2(9, 9),
   new Vector2(9, 1),
   new Vector2(3, 1),
   new Vector2(3, 0),
   new Vector2(10, 0),
   new Vector2(10, 10),
   new Vector2(1, 10),
   new Vector2(1, 0),
   ```
<img width="604" alt="image" src="https://github.com/Evryway/lir/assets/3191500/ce06e12d-8bfe-4276-a32c-313e885143c7">

   The result is: `(6.500, 5.000), (7.000, 10.000), (1.000, 0.000)`
   
Perhaps, it would be better to first identify an inner rectangle, then search for suitable rectangles around it (at the front, back, left, and right) to get the results. Here is a Python implementation (I'm sorry, I don't know C#):

```python
def fill_polygon(matrix, startx, starty):
    rows = len(matrix)
    cols = len(matrix[0])

    def dfs(x, y):
        if x < 0 or y < 0 or x >= rows or y >= cols or matrix[x][y] in (1, 2):
            return
        matrix[x][y] = 2
        dfs(x + 1, y)
        dfs(x - 1, y)
        dfs(x, y + 1)
        dfs(x, y - 1)

    dfs(startx, starty)

    return matrix


a = [
    [0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0],
    [1, 0, 0, 1, 0],
    [0, 1, 0, 1, 0],
    [0, 0, 1, 0, 0]
]

print(fill_polygon(a, 2, 1))
"""
[
    [0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0],
    [1, 2, 2, 1, 0],
    [0, 1, 2, 1, 0],
    [0, 0, 1, 0, 0]
]
"""


```

2. The efficiency is quite low when there are too many points, for example, over 1000 points.
   Maybe a simplification algorithm could be used for pre-processing: https://github.com/mourner/simplify-js
   Especially when there are arcs in the graph, using pre-processing could improve both the accuracy of the results and the computational efficiency.

3. When there are too few points, such as with a rhombus formed by 4 points, it is impossible to get a result. In this case, perhaps xs and ys could be expanded to 50 elements each.
   I did a test, and when the number of elements for x and y are both 50, the processing time is less than 10ms.

**Comment by Evryway** [comment]
Thank you for your report, ficapy.
Issues 2 and 3 can both be addressed prior to running the LIR algorithm, based on the knowledge of the incoming data set. Your suggestion of a simplify pre-process for complex geometry is good, and I'd recommend that before trying to identify the LIR. The same is true for very simple geometry, constructing duplicate points along existing edges is both sensible and outside the scope of the LIR algorithm.

I will investigate the labelling issue you have raised, thanks for identifying the problem.

**Comment by Evryway** [comment]
I've now addressed the cell interior labelling bug. If you'd like to test it, the latest version of mainline as of 20241210 has the relevant changes, and I've documented the changes here : https://www.evryway.com/largest-interior-2/

Thanks again for raising the issue!
